"""create apartment table

Revision ID: d2fe443810ef
Revises: 
Create Date: 2026-06-27 00:49:38.399337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2fe443810ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('object_type', sa.Integer(), nullable=True),
    sa.Column('room_count', sa.Integer(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('floor_num', sa.Integer(), nullable=True),
    sa.Column('floor_count', sa.Integer(), nullable=True),
    sa.Column('ceiling_height', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('condition', sa.Integer(), nullable=True),
    sa.Column('condition_text', sa.String(), nullable=True),
    sa.Column('toilet_type', sa.Integer(), nullable=True),
    sa.Column('furniture_type', sa.Integer(), nullable=True),
    sa.Column('former_dorm', sa.Boolean(), nullable=True),
    sa.Column('bail', sa.Boolean(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('sell_price_meter', sa.Float(), nullable=True),
    sa.Column('sell_currency', sa.Integer(), nullable=True),
    sa.Column('supply_source', sa.Integer(), nullable=True),
    sa.Column('flat_type', sa.Integer(), nullable=True),
    sa.Column('city', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('address_name', sa.String(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('district_text', sa.String(), nullable=True),
    sa.Column('house_num', sa.String(), nullable=True),
    sa.Column('intersection_name', sa.String(), nullable=True),
    sa.Column('coord_x', sa.Float(), nullable=True),
    sa.Column('coord_y', sa.Float(), nullable=True),
    sa.Column('geohash', sa.String(), nullable=True),
    sa.Column('krisha_id', sa.String(), nullable=True),
    sa.Column('load_source', sa.Integer(), nullable=True),
    sa.Column('memo_public', sa.String(), nullable=True),
    sa.Column('dt_create', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dt_modify', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_source_sourceid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartments')
    # ### end Alembic commands ###
